// Regenerate src/schema/<version>.ts from the published Launchpad OpenAPI specs.
//
// Source specs (published by github.com/goulinkh/launchpad-wadl-to-openapi):
//   https://goulinkh.github.io/launchpad-wadl-to-openapi/launchpad-<version>.openapi.yaml
//
// Usage: node scripts/generate.mjs [version ...]   (default: 1.0 beta devel)

import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const SPEC_BASE = "https://goulinkh.github.io/launchpad-wadl-to-openapi";
const DEFAULT_VERSIONS = ["1.0", "beta", "devel"];

const versions = process.argv.slice(2).length
  ? process.argv.slice(2)
  : DEFAULT_VERSIONS;

const outDir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "schema");
await mkdir(outDir, { recursive: true });

for (const version of versions) {
  const url = `${SPEC_BASE}/launchpad-${version}.openapi.yaml`;
  process.stdout.write(`Generating types for ${version} from ${url} ... `);
  const ast = await openapiTS(new URL(url));
  const header =
    `// Generated by \`npm run generate\` from ${url}\n` +
    `// Do not edit by hand.\n\n`;
  const file = join(outDir, `${version.replace(/\./g, "_")}.ts`);
  await writeFile(file, header + astToString(ast));
  process.stdout.write(`wrote ${file}\n`);
}
